openapi: '3.0.2'
info:
  title: 勉強会API
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /test:
    get:
      description: aaaaaaaaa
      responses:
        '200':
          description: OK
  /relation:
      get:
        responses:
          '200':
            description: OK
